### ISSUE TITLE
Shake with non 0 message length

### ISSUE THREAD

**Issue by lseekio** [mjosaarinen/tiny_sha3#3]
Trying to reproduce results from NIST Shake Byte oriented short messages.
https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/sha3/shakebytetestvectors.zip

Not having any luck with shake_update before shake_xof.

Can you offer an example how to use shake with non 0 message length.

**Comment by mjosaarinen** [comment]
nope
